app:
  bucket: ${AWS_S3_BUCKET:shawty}
  base-url: ${BASE_URL}
  storage: ${STORAGE_TYPE:S3}
  local-storage-path: ${LOCAL_STORAGE_PATH:/var/shawty/files}
quarkus:
  log:
    category:
      "de.merkeg.shawty":
        level: ${LOG_LEVEL:INFO}
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: ${DB_KIND:postgresql}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_URL:jdbc:${DB_KIND:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:shawty}}
  s3:
    # Endpoint für self-hosted S3 (z.B. MinIO): QUARKUS_S3_ENDPOINT_OVERRIDE=https://your-s3-host
    # Path-style access wird für die meisten self-hosted S3-Implementierungen benötigt
    path-style-access: ${AWS_S3_PATH_STYLE_OVERRIDE:true}
    aws:
      region: ${AWS_REGION:eu-central-1}
  http:
    limits:
      max-body-size: ${MAX_BODY_SIZE:1G}