quarkus:
  log:
    category:
      "de.merkeg.shawty":
        level: DEBUG
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: postgresql
    devservices:
      enabled: false
    username: shawty
    password: shawty
    jdbc:
      url: jdbc:postgresql://localhost:5432/shawty
  s3:
    devservices:
      enabled: false
app:
  base-url: http://localhost:8080/
  storage: LOCAL
  local-storage-path: /tmp/shawty
