quarkus:
  log:
    category:
      "de.merkeg.shawty":
        level: DEBUG
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: mariadb
    devservices:
      enabled: true
      port: 3306
      username: mariadb
      password: mariadb
      db-name: mariadb
  aws:
    devservices:
      localstack:
        port: 4566
  s3:
    devservices:
      enabled: true
      buckets:
        - shawty
      aws:
        credentials:
          type: static
          static-provider:
            access-key-id: test-key
            secret-access-key: test-secret
app:
  bucket: shawty
  base-url: http://localhost:8080/