quarkus:
  log:
    category:
      "de.merkeg.shawty":
        level: DEBUG
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: mariadb
    devservices:
      enabled: false
    username: root
    password: mariadb
    jdbc:
      url: jdbc:mariadb://localhost:3306/mariadb
  s3:
    endpoint-override: http://localhost:9000
    aws:
      region: eu-central-1
app:
  bucket: shawty
  base-url: http://localhost:8080/