quarkus:
  log:
    category:
      "de.merkeg.shawty":
        level: DEBUG
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: sqlite
    devservices:
      enabled: false
    jdbc:
      url: jdbc:sqlite:/Users/merkeg/Documents/dev/java/shawty/shawty.db
  s3:
    devservices:
      enabled: false
app:
  base-url: http://localhost:8080/
  storage: LOCAL
  local-storage-path: /tmp/shawty
