####
# This Dockerfile builds a container that runs the Quarkus application in JVM mode
# using a minimal Alpine-based JRE 21 image.
#
# Before building the container image run:
#   ./gradlew build
#
# Build the image:
#   docker build -f src/main/docker/Dockerfile.jvm -t quarkus/shawty-jvm .
#
# Run the container:
#   docker run -i --rm -p 8080:8080 quarkus/shawty-jvm
###
FROM eclipse-temurin:21-jre-alpine

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT [ "java", \
  "-Dquarkus.http.host=0.0.0.0", \
  "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", \
  "-jar", "/deployments/quarkus-run.jar" ]
