version: '3.7'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: shawty
      POSTGRES_PASSWORD: shawty
      POSTGRES_DB: shawty
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
#  minio:
#    image: minio/minio
#    entrypoint: sh
#    command: -c 'mkdir -p /export/shawty && /usr/bin/minio server /export'
#    volumes:
#      - ./s3-data:/export
#    environment:
#      MINIO_ACCESS_KEY: s3-access-key
#      MINIO_SECRET_KEY: s3-secret-key
#    ports:
#      - 9000:9000